
["General Settings"]
	#Add the name of the weapon you wanted to have staff casting animation here with the format mod_id:weapon_name
	staffWeapon = ["irons_spellbooks:blood_staff", "irons_spellbooks:ice_staff", "irons_spellbooks:graybeard_staff", "irons_spellbooks:artificer_cane", "irons_spellbooks:lightning_rod", "irons_spellbooks:magehunter", "irons_spellbooks:keeper_flamberge", "irons_spellbooks:spellbreaker", "irons_spellbooks:amethyst_rapier", "irons_spellbooks:hither_thither_wand"]
	#Enable or disable hiding item in hand while two-handed animation is playing
	hideTwoHandedItems = true
	#Enable or disable hiding item in the off-hand while staff animation is playing
	hideOffHandItems = true
	#How long the cooldown for casting spell should be after attacking/guarding? 0 is no cooldown and 1 is maximum cooldown based on your main weapon speed. For example sword has the attack speed of 16 ticks, so a default value of 0.5 will make the cooldown 8 ticks (1 second is 20 ticks, also please write 0 as 0.0)
	castingDelay = 0.0
	#Enable or disable spell cooldown when the spell is interrupted by guarding/blocking
	EnableSkillCooldownOnGuard = true
	#Enable or disable spell cancelling when using dodge skills like roll and step
	EnableDodgeCancelling = true
	#Enable or disable spell cooldown when the spell is interrupted by dodging
	EnableSkillCooldownOnDodge = true

