#重置招架成功/闪避成功判定的时间
#即招架成功/闪避成功结束后多长时间后自动重置普攻连段。
#Range: > 0
effect_tick = 20
#重置连段时间
#即动作结束后多长时间后自动重置普攻连段。
#Range: > 0
reset_tick = 16
#预存输入时间，仅客户端有效
#即在前一个动画未结束时，若提前按下按键，则会在这段时间内反复尝试请求执行。
#Range: > 0
reserve_tick = 8
#输入延迟时间，仅客户端有效。指按下按键后到执行技能的时间间隔。
#越长则对双键判定越有利，但单键触发时长也会受影响。
#Range: > 0
input_delay_tick = 4

