
[Implants]
	#Scales all implant humanity on craft (default: 1)
	implantHumanityScaling = 1.0
	#The maximum quality implants can reach. This is automatically overridden if the implant's max quality is set in its JSON config (default: 150)
	maxImplantQuality = 150.0
	#If enabled, implants will lose quality upon death and break if that quality reaches 0 (default: false)
	hardcoreImplants = false
	#Scales how much quality is lost on death (default: 10%)
	hardcoreImplantDamageScaling = 1.0

[General]
	#Disables the vanilla jump crit (default: true)
	disableVanillaCrit = true
	#If true, fall damage will be reset when gravity is negative (default: true)
	gravityFallDamage = true
	#Enables the Zoe critical hit (default: true)
	zoeCrit = true
	#If enabled, crits can only be dealt on a full sweep (default: true)
	zoeCritSweep = true
	#If enabled, knockback resistance will be calculated with crit knockback (default: false)
	zoeCritKnockback = true
	#Allows high-speed impact with blocks to cause an explosion (unreliable)
	collisionImpact = true
	#If enabled, will prevent the Volt attribute from dealing damage if the player's hand isn't empty (default: true)
	disableArmedVolt = true
	#The maximum chance for a Zoe crit. Any number above this will contribute to crit damage instead (default: 100)
	zoeMaxCritChance = 100.0

[Entities]
	#Scales how much extra damage mechanical mobs take from volt
	voltMechanicalDamageScaling = 1.5
	#The chances for a cyborg to drop an implant. Set to 0 to disable implant drops (default: 12.5)
	implantDropRate = 12.5
	#The chances of a cyborg being born with a trait. Set to 0 to disable Cyborg traits (default: 25)
	cyborgTraitChance = 25.0
	#The minimum amount of traits a Cyborg can have, granted it was selected to have traits (default: 1)
	minCyborgTraits = 1.0
	#The maximum of traits a cyborg is allowed to have (default: 1)
	maxCyborgTraits = 4.0
	#Dictates the damage reduction to mechanical mobs of damagetypes in the mechanical_resistant_to tag (default: 0.5)
	resistanceMechanicalDamageScaling = 0.5
	#Scales the stats of all mechanical mobs
	mechanicalMobStatScaling = 1.0

